### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'power_on'

### ISSUE THREAD

**Issue by Karraya** [adafruit/Adafruit_Python_BluefruitLE#27]
Hi I am trying to run any of your examples but I keep getting the following error no matter what example I try. Can you please explain what is going on? 

root@beaglebone:~/Adafruit_Python_BluefruitLE/examples# python low_level.py
Traceback (most recent call last):
  File "low_level.py", line 106, in <module>
    ble.run_mainloop_with(main)
  File "build/bdist.linux-armv7l/egg/Adafruit_BluefruitLE/bluez_dbus/provider.py", line 105, in run_mainloop_with
  File "build/bdist.linux-armv7l/egg/Adafruit_BluefruitLE/bluez_dbus/provider.py", line 120, in _user_thread_main
  File "low_level.py", line 38, in main
    adapter.power_on()
AttributeError: 'NoneType' object has no attribute 'power_on'

**Comment by dhalbert** [comment]
This library has been deprecated. Please update to use this new library:
https://github.com/adafruit/Adafruit_Blinka_bleio
If you continue to have this issue, please open a new issue in that repo.
