### ISSUE TITLE
ble.find_device name argument on Linux

### ISSUE THREAD

**Issue by subvertallchris** [adafruit/Adafruit_Python_BluefruitLE#39]
- OS: Ubuntu 16.04 Desktop
- Python Version: 2.7
- Bluez Version: 5.37-0ubuntu5.1

When using the commands `ble.find_device` or `find_devices`, I get an error if I include `name`. If I omit name, it finds my device and everything works.

This code:

```
device = ble.find_device(service_uuids=[UART_SERVICE_UUID], timeout_sec=1, name="MyCustomName")
```

Gives me this error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/mypath/src/uart/controller.py", line 90, in run
    ble.run_mainloop_with(setup)
  File "build/bdist.linux-x86_64/egg/Adafruit_BluefruitLE/bluez_dbus/provider.py", line 105, in run_mainloop_with
    raise_(self._exception[1], None, self._exception[2])
  File "build/bdist.linux-x86_64/egg/Adafruit_BluefruitLE/bluez_dbus/provider.py", line 120, in _user_thread_main
    self._return_code = target()
  File "/mypath/src/uart/controller.py", line 41, in setup
    device = ble.find_device(service_uuids=[UART_SERVICE_UUID], timeout_sec=1, name="MyCustomName")
  File "build/bdist.linux-x86_64/egg/Adafruit_BluefruitLE/interfaces/provider.py", line 135, in find_device
    found = self.find_devices(service_uuids, name)
  File "build/bdist.linux-x86_64/egg/Adafruit_BluefruitLE/interfaces/provider.py", line 114, in find_devices
    if device.name == name:
  File "build/bdist.linux-x86_64/egg/Adafruit_BluefruitLE/bluez_dbus/device.py", line 150, in name
    return self._props.Get(_INTERFACE, 'Name')
  File "/home/user/.local/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/home/user/.local/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: org.freedesktop.DBus.Error.InvalidArgs: No such property 'Name'
```

If I remove the name, it eventually finds my device and boots successfully.

Possibly related, I can't use the `DeviceInformation` function. 

This code:

```
device = ble.find_device(service_uuids=[UART_SERVICE_UUID], timeout_sec=1)
print DeviceInformation(device))
```

Results in this error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/mypath/src/uart/controller.py", line 95, in run
    ble.run_mainloop_with(setup)
  File "build/bdist.linux-x86_64/egg/Adafruit_BluefruitLE/bluez_dbus/provider.py", line 105, in run_mainloop_with
    raise_(self._exception[1], None, self._exception[2])
  File "build/bdist.linux-x86_64/egg/Adafruit_BluefruitLE/bluez_dbus/provider.py", line 120, in _user_thread_main
    self._return_code = target()
  File "/mypath/src/uart/controller.py", line 50, in setup
    print DeviceInformation(device)
  File "build/bdist.linux-x86_64/egg/Adafruit_BluefruitLE/services/device_information.py", line 58, in __init__
    self._manufacturer = self._dis.find_characteristic(MANUFACTURER_CHAR_UUID)
AttributeError: 'NoneType' object has no attribute 'find_characteristic'
```

I know next to nothing about any of this, but looking at my D-Bus through [DFeet](https://wiki.gnome.org/Apps/DFeet), I can find my device under /org/bluez/hci0/my-mac-addr/ and its Properties have a Name key which has the name I'm expecting to find.

Ultimately, what I'm trying to do is try to ensure that a host machine only connects to a specific Bluefruit. In a perfect world, I'd put the MAC address in a config file. In an even more perfect world, I'd ensure that this Bluefruit can't connect to another host machine. If there's a better way to do this that works around this problem, I'm happy to go that route.

Appreciate your help with this! Thank you for this fantastic library and product.

**Comment by exinmusic** [comment]
Any heading on this? All research I've done turns up bug reports from a few years back and it getting solved.
Getting same results with:
Raspberrypi Zero W 1.1
Raspberry Pi OS 2020-05-27 (Kernel 4.19) Buster
Using bluez version 5.50

installed Adafruit Python Bluefruitle lib both from git and apt with same results.

**Comment by ladyada** [comment]
honestly, this library is deprecated and we'll be archiving it soon. you should try out our new `bleio` library which is based on `bleak` - it works with all platforms, Py3 and we have a bunch of BLE libraries that work with it
https://github.com/adafruit/Adafruit_Blinka_bleio
and
https://github.com/adafruit/Adafruit_CircuitPython_BLE/
however, its beta and somewhat undocumented

**Comment by dhalbert** [comment]
This library has been deprecated. Please update to use this new library:
https://github.com/adafruit/Adafruit_Blinka_bleio
If you continue to have this issue, please open a new issue in that repo.
