### ISSUE TITLE
dbus.exceptions.DBusException   No such property 'Characteristics'

### ISSUE THREAD

**Issue by Tasm-Devil** [adafruit/Adafruit_Python_BluefruitLE#40]
I get a Exception when running the example script. Same [here](https://github.com/adafruit/Adafruit_Python_BluefruitLE/issues/23)!

```
me@mypc:~/Adafruit_Python_BluefruitLE-master/examples$ python3 uart_service.py 
Using adapter: Yoga
Disconnecting any connected UART devices...
Searching for UART device...
Connecting to device...
Discovering services...
Traceback (most recent call last):
  File "uart_service.py", line 85, in <module>
    ble.run_mainloop_with(main)
  File "/home/pascal/.local/lib/python3.6/site-packages/Adafruit_BluefruitLE/bluez_dbus/provider.py", line 105, in run_mainloop_with
    raise_(self._exception[1], None, self._exception[2])
  File "/home/pascal/.local/lib/python3.6/site-packages/future/utils/__init__.py", line 416, in raise_
    raise exc
  File "/home/pascal/.local/lib/python3.6/site-packages/Adafruit_BluefruitLE/bluez_dbus/provider.py", line 120, in _user_thread_main
    self._return_code = target()
  File "uart_service.py", line 59, in main
    uart = UART(device)
  File "/home/pascal/.local/lib/python3.6/site-packages/Adafruit_BluefruitLE/services/uart.py", line 50, in __init__
    self._tx = self._uart.find_characteristic(TX_CHAR_UUID)
  File "/home/pascal/.local/lib/python3.6/site-packages/Adafruit_BluefruitLE/interfaces/gatt.py", line 48, in find_characteristic
    for char in self.list_characteristics():
  File "/home/pascal/.local/lib/python3.6/site-packages/Adafruit_BluefruitLE/bluez_dbus/gatt.py", line 56, in list_characteristics
    paths = self._props.Get(_SERVICE_INTERFACE, 'Characteristics')
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.InvalidArgs: No such property 'Characteristics'
```

I installed this module with `pip3 install --user Adafruit-BluefruitLE`

Any help? Maybe just updating the [pypi package](https://pypi.org/project/Adafruit-BluefruitLE/)

**Comment by fahad80** [comment]
Here is the fix:
https://github.com/donatieng/Adafruit_Python_BluefruitLE/commit/af46b05cbcfd82110c8bbd08ed3d483de128fed1

**Comment by dhalbert** [comment]
This library has been deprecated. Please update to use this new library:
https://github.com/adafruit/Adafruit_Blinka_bleio
If you continue to have this issue, please open a new issue in that repo.
